# Map image file
image: fbm1_map.pgm

# Resolution of the map, meters / pixel
resolution: 0.001

# The 2-D pose of the lower-left pixel in the map
origin: [-0.1, -0.1, 0]

# Negate white/black free/occupied semantics?
negate: 0

# Occupied/free pixel thresholds
occupied_thresh: 0.65
free_thresh: 0.196

